# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb685010106bc7818dfa721859747dba26e53fa8cddbe77835612ecdd65b4fc73abac9eb51e73d0eb2e947bbb306354fd6e94514fdac9a9f81a8e2279b5edfa4

test:
  secret_key_base: dd1a73d9059709070b3537b61f02a82b2384d4fbce1034e5556b19487c2c9d7db1deb7197a0452bd2b40b6609428bbaaf0ca1c093cf899e2b4dfdb3bd9087d2b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
